Search 2
jml/holborn pull request #2
Opened 2016-09-28 12:56 UTC by teh

This exposes a search handler + has a few inconsequential cleanups attached.

2016-09-29 13:45 UTC, jml requested changes
Thanks! 

I'm really glad you split this up, was a lot of stuff to review. Would welcome a chance to review changes before merging.

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API.hs
> +                    :<|> Holborn.API.CreateRepository.server conf
Thanks for increasing consistency. Much appreciated!

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +data BrowseError = NotFound | InvalidSearchQuery
Maybe include the invalid query here?

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +search _maybeUsername owner repo query  = do
Nit: I'd just go `_`, given that `Maybe Username` is right above it.

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API/Internal.hs
> +  pure $ "http://" <> repoHostname <> ":" <> fromShow repoPort <> "/v1/repos/" <> toUrlPiece repoId
No change required.

If we were using Servant on the client side (i.e. from api to repo), then we could actually really easily integrate an HTTP client manager to get all of this.

2016-09-29 13:45 UTC, jml commented on holborn-common-types/holborn-common-types.cabal
>        Holborn.JSON.SSHRepoCommunication
Was the plan to also move the others later?

2016-09-29 13:45 UTC, jml commented on holborn-repo/lib/Holborn/Repo/Search.hs
> +    _ -> undefined
Why do this?

2016-09-29 13:45 UTC, jml commented on holborn-repo/lib/Holborn/Repo/Search.hs
> +  traceShowM search
Maybe best to keep debug code out of master & just apply locally as needed?

2016-09-29 13:45 UTC, jml commented on holborn-repo/lib/Holborn/Repo/SearchAPI.hs
> +  blobs <- traverse (\p -> withRepository repo (getBlob refMaster (pathSegments p))) paths
I didn't realise we had `refMaster`. Hmm. 

No action required.

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +         :> Capture "repo" RepoName
What we should be doing is aggregating all of the `(Header "x-dex-name" ... RepoName)` bit and fetching the repo there, allowing the other endpoints to be expressed in terms of existing authenticated repos, reducing the duplication.

Probably OK for a separate PR though.

2016-09-29 13:45 UTC, jml commented on holborn-repo/lib/Holborn/Repo/Search.hs
> +  void (P.string ((textToString (toUrlPiece ref)) <> ":"))
While you're here, want to clean up the deprecation warnings?

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +         :> Get '[JSON, RenderedJson] Value
This makes me sad. 

Given this is currently under discussion elsewhere, I think it shouldn't be changed in this review.

If we were to stick with Servant as our main way of expressing APIs, then we would need to:
- define the APIs and the types therein as "interface" packages from the server implementations[1]
- import these into the server implementations and implement them
- import them into the clients (holborn-ssh, holborn-api, hcl maybe) and use them there

[1] Technically we don't _have_ to have them in separate packages, but it will make compile times faster and make the boundary lines more clear.

2016-09-29 13:45 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +  -- TODO this should probably be an RPC request.
It is an RPC request. What do you mean?

2016-09-29 16:21 UTC, teh reviewed
also had to do a bunch of fixing for protolude

2016-09-29 16:21 UTC, teh commented on holborn-api/lib/Holborn/API/Browse.hs
> +         :> Get '[JSON, RenderedJson] Value
Yea I was thinking the same thing. Have a project repository that's the equivalent of the "proto" dir in googel3. It contains all the API combinators, and data structures we send around (+Generic, JSON & maybe some more efficient protocol like "binary" instances)

2016-09-29 16:21 UTC, teh commented on holborn-api/lib/Holborn/API/Browse.hs
> +         :> Capture "repo" RepoName
Sure, feel free to shuffle around - As mentioned a few times before I'm not bothered by repetition and I even prefer it over chasing definitions sometimes.

2016-09-29 16:21 UTC, teh commented on holborn-api/lib/Holborn/API/Browse.hs
> +data BrowseError = NotFound | InvalidSearchQuery
done

2016-09-29 16:21 UTC, teh commented on holborn-api/lib/Holborn/API/Browse.hs
> +search _maybeUsername owner repo query  = do
done

2016-09-29 16:21 UTC, teh commented on holborn-api/lib/Holborn/API/Browse.hs
> +  -- TODO this should probably be an RPC request.
It's technically one but as discussed in the doc it should look like one, too `callSearch remoteServer query` or sth like that.

2016-09-29 16:21 UTC, teh commented on holborn-api/lib/Holborn/API/Internal.hs
> +  pure $ "http://" <> repoHostname <> ":" <> fromShow repoPort <> "/v1/repos/" <> toUrlPiece repoId
What would the manager do that we aren't doing here? Assembling the URL from fragments?

2016-09-29 16:21 UTC, teh commented on holborn-common-types/holborn-common-types.cabal
>        Holborn.JSON.SSHRepoCommunication
Yea, whenever I see an obvious one I'll move it

2016-09-29 16:21 UTC, teh commented on holborn-repo/lib/Holborn/Repo/Search.hs
> +  traceShowM search
accident, removed

2016-09-29 16:21 UTC, teh commented on holborn-repo/lib/Holborn/Repo/Search.hs
> +    _ -> undefined
so it blows up if I do something stupid by accident - changed to error

2016-09-29 16:21 UTC, teh commented on holborn-repo/lib/Holborn/Repo/Search.hs
> +  void (P.string ((textToString (toUrlPiece ref)) <> ":"))
done

2016-09-29 16:21 UTC, teh commented on holborn-repo/lib/Holborn/Repo/SearchAPI.hs
> +  blobs <- traverse (\p -> withRepository repo (getBlob refMaster (pathSegments p))) paths
added a few days ago, we had a bunch of random code that referred to master - still not good e.g. I figured out that you can have repos without `master` so we really need to go for master and that doesn't exist the last-updated branch.

maybe you can even have no-branch repos, not sure what to do then

2016-09-29 16:32 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +  q <- maybe (throwHandlerError (InvalidSearchQuery (maybe "" identity query))) pure query
Nit: `fromMaybe x` is equivalent to `maybe x identity`

2016-09-29 16:32 UTC, jml commented on holborn-prelude/default.nix
> -{ mkDerivation, base, mtl, protolude, safe, stdenv, tasty
Oops. Sorry for missing this.

2016-09-29 16:32 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +  -- TODO this should probably be an RPC request.
Oh I see.

2016-09-29 16:33 UTC, jml commented on holborn-api/lib/Holborn/API/Browse.hs
> +         :> Get '[JSON, RenderedJson] Value
Cool! I outlined something like that in a Jul 11 email "holborn packages & dependencies".

2016-09-29 16:38 UTC, jml commented on holborn-api/lib/Holborn/API/Internal.hs
> +  pure $ "http://" <> repoHostname <> ":" <> fromShow repoPort <> "/v1/repos/" <> toUrlPiece repoId
Basically make it look like an RPC API, e.g. https://github.com/jml/holborn/blob/master/holborn-ssh/holborn-connect-repo/Main.hs#L64-L94, which defines the `checkRepoAccess` method and then calls it.

The "Manager" is just a way of doing http client connection pooling. The other bits put all of the serialization & URL handling under the covers. 

If we did this (which would depend on splitting out interfaces) and we also did the reduced duplication that I describe above, the browse & search functions could just take a `HolbornRepoClient` as their first parameter, and call methods on it.

2016-09-29 16:39 UTC, jml commented on holborn-common-types/holborn-common-types.cabal
>        Holborn.JSON.SSHRepoCommunication
I guess what I mean is, what's the distinction in your head between stuff in `Holborn.JSON` and stuff in `Holborn.CommonTypes`?

2016-09-29 16:41 UTC, jml commented on holborn-repo/lib/Holborn/Repo/SearchAPI.hs
> +  blobs <- traverse (\p -> withRepository repo (getBlob refMaster (pathSegments p))) paths
Yeah. I've thought a lot about this in other contexts (e.g. difftodo). We could have a concept of a default branch, like GitHub does. GitHub sets the first pushed branch to default. Having `refMaster` as a variable is probably a better thing than literal `"master"` everywhere. When we fix it we can follow the trail of the compile errors.

2016-09-29 16:41 UTC, jml commented
> also had to do a bunch of fixing for protolude

You didn't have to, but I'm grateful you did.

2016-09-29 16:44 UTC, jml commented
Thanks for going above & beyond in cleaning up warnings.

2016-09-29 16:44 UTC, jml approved these changes

2016-09-30 13:56 UTC, teh commented on holborn-common-types/holborn-common-types.cabal
>        Holborn.JSON.SSHRepoCommunication
It's not a super clear line but for me JSON.X is exclusively for client communication, and CommonTypes can be used for serialization but are also used a lot internally (e.g. to talk to the DB, or just do logic stuff)

2016-09-30 13:57 UTC, teh commented on holborn-repo/lib/Holborn/Repo/SearchAPI.hs
> +  blobs <- traverse (\p -> withRepository repo (getBlob refMaster (pathSegments p))) paths
Didn't know the default branch behaviour. Let's do that, I'll make it part of a soonish branch

2016-09-30 14:13 UTC, teh commented on holborn-api/lib/Holborn/API/Browse.hs
> +         :> Get '[JSON, RenderedJson] Value
OK, re-read that email. I'm + 1 but I'd prefer one api package instead of all the "holborn-*-api" cabal packages.

2016-09-30 14:13 UTC, merged